name: Publish Docker image

on:
  push:
    branches: [master]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@ec9cdf07d570632daeb912f5b2099cb9ec1d01e6
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@3343011071fa59c64a174cc6aa415dc13b31b7b2
        with:
          images: hajaalin/cellprofiler-docker
      
      - name: Build and push Docker image
        uses: docker/build-push-action@35434f557ad77672899d67f7992fb5560bda1071
        with:
          context: ./v4.2.5
          push: true
          tags: v4.2.5
          labels: ${{ steps.meta.outputs.labels }}
